set_bootargs_nfs=setenv bootargs mem=<MEM> console=tty0,115200 console=ttyUSB0,115200 console=<CONSOLE>,<BRATE> rw init=init root=/dev/nfs ip=<TARGET_IP>:<SERVER_IP>:<GATEWAY_IP>:<NETMASK_IP>:<HOSTNAME>:eth0 nfsroot=<NFSROOTPATH> <APPEND>

bootpart=0:1
fdtfile=omap4-panda-es.dtb

uenvboot_rom=run mmcboot

loadfile_nfs=tftpboot ${bootaddr} ${bootfile};tftpboot ${fdtaddr} ${fdtfile} 
uenvboot_nfs=run loadfile_nfs; run set_bootargs_nfs; bootz ${bootaddr} - ${fdtaddr}


uenvboot=run <BOOT_TYPE>

